### ISSUE TITLE
Not working with Mega2560

### ISSUE THREAD

**Issue by DamianBroj** [thebradleysanders/ESPHome-Arduino-Port-Expander#1]
Hi Bradley, i have just tried to upload .ino and .h into my Mega2560 + Nodemcu and it is not flying together. Is the current commit the working one?

**Comment by thebradleysanders** [comment]
I see, yes the current commit is what I have working. Try changing your I2C pins:

```
i2c:
  - id: i2c_component1
    sda: 2
    scl: 4
```
